version: '2'
services:
  db:
    image: mongo:3.0
    command: mongod --smallfiles --quiet
    ports:
      - "27017:27017"
  web:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - db
    links:
      - db
